[toolchain]
anchor_version = "0.31.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vesting = "6sXdNbamry34fHvbZbMeheviGg2TKa3fVKs9okHyRWs9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
